---
apiVersion: v1
kind: Secret
metadata:
  name: jxrht-gh2-3-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevRHEL/jxrht-gh2-3-gateway-gitops
